AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'config/application.rb'
    - 'bin/*'
    - 'spec/spec_helper.rb'
    - 'db/migrate/*'
    - 'config/initializers/devise.rb'
    - 'app/models/ability.rb'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'config.ru'

Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false