AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'
    - 'config/application.rb'
    - 'bin/*'
    - 'spec/spec_helper.rb'
    - 'db/migrate/*'
    - 'config/initializers/devise.rb'

Documentation:
  Enabled: false

Metrics/LineLength:
  Enabled: false
  