rvm: '2.1.5'
script: bundle exec rspec spec

before_script:
  - psql -c 'create database yelp_test;' -U postgres

# script:
#  - bundle exec bin/rake db:create
#  - bundle exec bin/rake db:migrate
#  - bundle exec rspec spec